runtime: python27
api_version: 1
threadsafe: true

handlers:

# statics
####################################
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js


# catch-all
####################################
- url: /.*
  script: python.main.app


# libraries
####################################

libraries:
- name: jinja2
  version: 2.6

# skip these files
####################################

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
